version: '2'
services:
  web:
    build: .
    image: actioncable-examples:latest
    command: ./bin/rails s
    environment:
      - SECRET_KEY_BASE=c4f64de223e7a916ae10188c9db279869e3fe2c9ef5789b3a7271acdc70362a04e0de81bb2f4e691dd9dfa3e69fe1d8b36137613a18046c336fef600f19c5e50
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - ACTION_CABLE_URI=ws://localhost:28080
      - ACTION_CABLE_ALLOWED_REQUEST_ORIGINS=http://localhost:3000      
      - REDIS_URL=redis://redis:6379
    ports:
      - 3000:3000

  cable:
    image: actioncable-examples:latest
    command: ./bin/cable
    environment:
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY_BASE=c4f64de223e7a916ae10188c9db279869e3fe2c9ef5789b3a7271acdc70362a04e0de81bb2f4e691dd9dfa3e69fe1d8b36137613a18046c336fef600f19c5e50
      - ACTION_CABLE_URI=ws://localhost:28080"
      - ACTION_CABLE_ALLOWED_REQUEST_ORIGINS=http://localhost:3000
      - RAILS_LOG_TO_STDOUT=true
    ports:
      - 28080:28080
    depends_on:
      - redis
      - web

  redis:
    image: redis:latest
